### ISSUE TITLE
parseNotification fails

### ISSUE THREAD

**Issue by soulchild** [Dexus/node-sofort#1]
Somehow parseNotification() in the provided example doesn't work for me:

```
./node_modules/node-sofort/lib/sofort.js:183
						throw new SofortException('Error postData', e.message);
						^
SofortException: Error postData -> Error postData -> unknown API error
```

Can you confirm this? If yes, I'd take a look at fixing the underlying issue.

**Comment by soulchild** [comment]
Well, it turned out that I handed in an incorrect transaction ID which causes the error. The error is misleading though, maybe we can work out a better way of telling the user what really went wrong? In case of an invalid transaction ID, the Sofort API returns an empty transactions tag:

```xml
<?xml version="1.0" encoding="UTF-8" ?>\n<transactions />
```

**Comment by Dexus** [comment]
Hi, thank you.

You are free to make a PR if you have a better idea for a user notice.
If i have some more time i will look to make it a better to tell whats wrong.

**Comment by soulchild** [comment]
Adding a custom error for invalid transaction ids seems pretty straightforward.

On a related note, I seem unable to catch any errors thrown by your module. I reckon it's because you're using async.waterfall() and instead of throwing errors you should be handing them to the passed-in callback. So, for instance, this:

```js
throw new SofortCodeException(result.errors.error[0].code);
```
becomes
```js
callback(new SofortCodeException(result.errors.error[0].code));
```

Does that make sense?

**Comment by Dexus** [comment]
Maybe is this #2 a good method to work on it...

**Comment by soulchild** [comment]
Oops, didn't see that one. Just finished [this](https://github.com/soulchild/node-sofort). ;-)

**Comment by soulchild** [comment]
Do you want me to open a pull request as well so you can decide which implementation works best? My fork cleans up the error messages, adds a dedicated error for invalid transaction ids and removes all try/catch occurrences. I also updated the examples.

**Comment by Dexus** [comment]
no need to do, i pull and meshup to get the best result.

**Comment by soulchild** [comment]
:+1:

**Comment by Dexus** [comment]
@soulchild why you think its better to remove the try catch?
It is possible that the `parseXmlString` crash with an exception, that is why i use try and return in this fail the error.

**Comment by Dexus** [comment]
@soulchild sorry that your ref is gone on commit...

**Comment by soulchild** [comment]
parseXmlString uses the same Node-style error-first callback approach and as far as I can tell doesn't throw errors on its own. That's why I figured the try/catch is unnecessary. If the parsing fails, we'll get an error in the callback. 

But maybe you're right and it's safer to continue catching lower-level errors and pass them back via the parseNotification() callback to not bring everything down in case something unexpected happens...

**Comment by robofish** [comment]
sadly it still does throw: https://github.com/Leonidas-from-XIV/node-xml2js/blob/master/lib/xml2js.js#L509

@soulchild we seem to have some great timing right here :sweat_smile:

**Comment by soulchild** [comment]
Argh! Good thing, dexus kept the try/catch then! :smile: Are you planning on releasing a new version of the npm straight away, @Dexus? As far as I'm concerned, we can close this issue.

**Comment by Dexus** [comment]
;) yes at weekend i will release the new version.

Von meinem iPhone gesendet

**Comment by soulchild** [comment]
:+1:

**Comment by smith64fx** [comment]
Hmm I also have this problem. I cannot even catch the error. =/

**Comment by Dexus** [comment]
@smith64fx wo hakt es den? Also es wird immer ein `err` in den Funktionen zurück gegeben wenn ein Fehler auftritt.
Aber vielleicht, sagst du welche version du nutzt und ich kann dann ggf. dagegen prüfen. Ich nutze selber die Lib in 4.x LTS und 6.x last stable.

**Comment by Dexus** [comment]
Btw here you get the raw body for the notification with express:

https://coderwall.com/p/qrjfcw/capture-raw-post-body-in-express-js

Von meinem iPhone gesendet
