### ISSUE TITLE
Unknown API Error

### ISSUE THREAD

**Issue by smith64fx** [Dexus/node-sofort#3]
Hi,
Unfortunately I cannot get to work with NodeSofort.

I get this error:
```
{ [SofortException: Error postData -> unknown API error]
  message: 'Error postData -> unknown API error',
  name: 'SofortException' }

/Users/smith/Git/node-sofort/node_modules/node-sofort/lib/sofort.js:184
						throw new SofortException('Error postData', e.message);
						^
SofortException: Error postData -> Error postData -> unknown API error
```

**Comment by Dexus** [comment]
Hi,
can you provide your node version?

And the error happens when you receive an notification right?

I think you don't send the correct XML to sofort.com.

Maybe you can give a sample of your implementation?

Regards

Von meinem iPhone gesendet

**Comment by smith64fx** [comment]
Mein Fehler. Hab dein Test Code kopiert.
Der 2. Teil verursacht den Fehler:

```
Sofort.parseNotification('<?xml version="1.0" encoding="UTF-8" ?><status_notification><transaction>27276-146697-55E48EAD-A3EB</transaction><time>2015-08-30T22:30:29+02:00</time></status_notification>',function(err,result){
    if (err) return console.log(err);
    console.log(util.inspect(result, {showHidden: false, depth: null}));
});
```


Danke nochmal für die tolle Arbeit, das erleichter uns grade einiges enorm! (Machen grade ein E-Commerce System mit Angular2 und NodeJS)

**Comment by Dexus** [comment]
Hehe, kein problem.

Viel erfolg und berichte gerne wenn man sich was ansehen kann. Würde gerne sehen wo mein Code neben meinen Projekten im einsatz ist. :)

Closes #3

Von meinem iPhone gesendet
