### ISSUE TITLE
Guide klarna?

### ISSUE THREAD

**Issue by ockang** [Dexus/node-sofort#6]

**Comment by Dexus** [comment]
Some more text and details about what you looking for will be nice.

**Comment by ockang** [comment]
I need to run the klarna checkout with this api is functional for it?

**Comment by Dexus** [comment]
It works for the sofort.com api. Don‘t know why it should not work since klarna has take sofort.com

Regards

**Comment by ockang** [comment]
then it would work, I'll do the corresponding tests

**Comment by ockang** [comment]
I have the problem of 401 not authorized, copy the uid and password, I would need some guidance on how to get these credentials well. you want the problem is that
